// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUh3qCDGQGx7GHxTq-PtCXYkdbzhPsKA',
    appId: '1:943617943568:web:f7a3aefd7f9cb6e4db0295',
    messagingSenderId: '943617943568',
    projectId: 'moviescout-se380',
    authDomain: 'moviescout-se380.firebaseapp.com',
    storageBucket: 'moviescout-se380.firebasestorage.app',
    measurementId: 'G-1CXVEDHDY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI3h_qxl6vHGyYiIbTEmU7KYWy1ucG9mk',
    appId: '1:943617943568:android:8318a2aab72a6119db0295',
    messagingSenderId: '943617943568',
    projectId: 'moviescout-se380',
    storageBucket: 'moviescout-se380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUdCH99178o1u6DyFH5yucWc5OjlNi1k',
    appId: '1:943617943568:ios:7c1e4d50e3401042db0295',
    messagingSenderId: '943617943568',
    projectId: 'moviescout-se380',
    storageBucket: 'moviescout-se380.firebasestorage.app',
    iosBundleId: 'com.example.filmdeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZUdCH99178o1u6DyFH5yucWc5OjlNi1k',
    appId: '1:943617943568:ios:7c1e4d50e3401042db0295',
    messagingSenderId: '943617943568',
    projectId: 'moviescout-se380',
    storageBucket: 'moviescout-se380.firebasestorage.app',
    iosBundleId: 'com.example.filmdeneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlUh3qCDGQGx7GHxTq-PtCXYkdbzhPsKA',
    appId: '1:943617943568:web:7d3fce00a3452d40db0295',
    messagingSenderId: '943617943568',
    projectId: 'moviescout-se380',
    authDomain: 'moviescout-se380.firebaseapp.com',
    storageBucket: 'moviescout-se380.firebasestorage.app',
    measurementId: 'G-GW58NWXHMD',
  );
}
